Types and operators hw
Ivstupin/AQA_MTS pull request #1
Opened 2023-11-18 07:37 UTC by Ivstupin

Домашняя работа по теме Основы типов и операторы, Ступин Иван, группа QAС05-onl.

2023-11-20 21:43 UTC, wildpioneer requested changes

2023-11-20 21:43 UTC, wildpioneer commented on TypesAndOperatrs/Program.cs
> +
Ты проверил и вывел сообщение о недопустимости операции деления на 0 и после этого продолжаешь выполнение программы - это не верно

2023-11-20 21:43 UTC, wildpioneer commented on TypesAndOperatrs/Program.cs
> +if (userValue >= -40 && userValue <= -10)
Отсутствует проверка, что введенное число находиться в диапазоне от -50 до 50

2023-11-20 21:43 UTC, wildpioneer commented on TypesAndOperatrs/Program.cs
> +if (evenOrNote % 2 != 0)
Ну пускай ;)

2023-11-20 21:43 UTC, wildpioneer commented on TypesAndOperatrs/Program.cs
> +
3 пустые строки - специально или просто так? Нужно использовать единообразие по всему коду

2023-11-25 15:15 UTC, Ivstupin commented on TypesAndOperatrs/Program.cs
> +
Исправил

2023-11-25 15:15 UTC, Ivstupin commented on TypesAndOperatrs/Program.cs
> +if (userValue >= -40 && userValue <= -10)
Исправил

2023-12-11 13:52 UTC, wildpioneer commented
Проверено

2023-12-11 13:52 UTC, wildpioneer commented
Не могу закрыть твой PR почему-то - ты меня добавил в этот проект в колобораторы?

2024-01-29 10:03 UTC, wildpioneer commented
Закрой этот PR сам - у меня нет прав

2024-01-29 10:18 UTC, closed without merging